// lib/majors.ts
// Comprehensive list of UTA (University of Texas at Arlington) majors
// Used in onboarding and profile edit forms

export const UTA_MAJORS = [
  // College of Engineering
  'Aerospace Engineering',
  'Architectural Engineering',
  'Biomedical Engineering',
  'Civil Engineering',
  'Computer Engineering',
  'Computer Science',
  'Construction Management',
  'Electrical Engineering',
  'Industrial Engineering',
  'Mechanical Engineering',
  'Resource and Energy Engineering',
  'Software Engineering',

  // College of Business
  'Accounting',
  'Business Administration',
  'Economics',
  'Finance',
  'Information Systems',
  'Management',
  'Marketing',
  'Operations Management',
  'Real Estate',
  'Supply Chain Management',

  // College of Science
  'Biochemistry',
  'Biology',
  'Chemistry',
  'Data Science',
  'Environmental Science',
  'Geology',
  'Mathematics',
  'Medical Laboratory Science',
  'Microbiology',
  'Physics',
  'Psychology',

  // College of Liberal Arts
  'Anthropology',
  'Art History',
  'Communication Studies',
  'Communication Technology',
  'Criminology',
  'English',
  'French',
  'History',
  'Linguistics',
  'Modern Languages',
  'Music',
  'Philosophy',
  'Political Science',
  'Sociology',
  'Spanish',
  'Theatre Arts',
  'Visual Art and Design',

  // College of Education
  'Curriculum and Instruction',
  'Educational Leadership',
  'Exercise Science',
  'Kinesiology',
  'Special Education',

  // College of Nursing and Health Innovation
  'Health Care Administration',
  'Nursing',
  'Public Health',

  // College of Architecture, Planning and Public Affairs
  'Architecture',
  'City and Regional Planning',
  'Interior Design',
  'Landscape Architecture',
  'Public Administration',
  'Urban and Public Affairs',

  // School of Social Work
  'Social Work',

  // Interdisciplinary / Other UTA programs
  'Aerospace Studies',
  'Asian Studies',
  'Cybersecurity',
  'Film and Video Production',
  'Global Studies',
  'Journalism',
  'Military Science',
  'Sustainability',
  'University Studies',
  'Women\'s and Gender Studies',

  // Common additional majors (other universities)
  'Actuarial Science',
  'Agricultural Science',
  'Artificial Intelligence',
  'Astronomy',
  'Athletic Training',
  'Bioinformatics',
  'Biostatistics',
  'Botany',
  'Business Analytics',
  'Chemical Engineering',
  'Cognitive Science',
  'Communications',
  'Computer Engineering Technology',
  'Creative Writing',
  'Dental Hygiene',
  'Early Childhood Education',
  'Ecology',
  'Education',
  'Electrical Engineering Technology',
  'Emergency Management',
  'Engineering Technology',
  'Entrepreneurship',
  'Environmental Engineering',
  'Fashion Design',
  'Film Studies',
  'Food Science',
  'Forensic Science',
  'Game Design',
  'Geographic Information Systems',
  'Geography',
  'Graphic Design',
  'Health Sciences',
  'Hospitality Management',
  'Human Resources',
  'Information Technology',
  'International Business',
  'International Relations',
  'Library Science',
  'Marine Biology',
  'Mass Communication',
  'Materials Science',
  'Mechanical Engineering Technology',
  'Media Studies',
  'Molecular Biology',
  'Neuroscience',
  'Nuclear Engineering',
  'Nutrition',
  'Occupational Therapy',
  'Petroleum Engineering',
  'Pharmaceutical Sciences',
  'Pharmacy',
  'Physical Therapy',
  'Pre-Dentistry',
  'Pre-Law',
  'Pre-Medicine',
  'Pre-Veterinary',
  'Robotics',
  'Sport Management',
  'Statistics',
  'Systems Engineering',
  'Telecommunications',
  'Zoology',
].sort()